"""
make_sample_data.py — generates tests/fixtures/sample_anonymized.xlsx

Produces a minimal but structurally faithful Excel fixture (3 fictional
respondents) that exercises the full convert_data → clean_data →
generate_all_reports pipeline.  Safe to commit: no real respondent data.

Usage:
    python scripts/make_sample_data.py
"""

from pathlib import Path

import openpyxl

OUT = (
    Path(__file__).resolve().parents[1]
    / "tests"
    / "fixtures"
    / "sample_anonymized.xlsx"
)

# ---------------------------------------------------------------------------
# Column headers — identical to the real MasterDatabase.xlsx (row 1, 0-indexed)
# ---------------------------------------------------------------------------
HEADERS = [
    "SubmitDate",
    "ReportSent",
    "Name:",
    "Function:",
    "Company name:",
    "Country",
    "E-mail address",
    "Version",
    "Sector",
    "Subsector",
    "Size (number of employees)",
    "Value strategy",
    "Where is the power in the chain?",
    "Position in the value chain",
    "B2B-B2C?",
    "# competitors",
    "# suppliers",
    "# customers",
    "# products-SKUs",
    "Customer order decoupling point",
    "Culture",
    "Type of company",
    "Geographical footprint supply network",
    "Geographical footprint customers",
    # Upstream ---------------------------------------------------------------
    "Up - R1a",
    "Up - R1b",
    "Up - R1c",
    "Up - R1",
    "Up - R2",
    "Up - R3",
    "Up - R4",
    "Up - R5",
    "Up - R",
    "Up - C1a",
    "Up - C1b",
    "Up - C1c",
    "Up - C1",
    "Up - C2",
    "Up - C3",
    "Up - C4",
    "Up - C",
    "Up - F1a",
    "Up - F1",
    "Up - F2a",
    "Up - F2b",
    "Up - F2",
    "Up - F3a",
    "Up - F3b",
    "Up - F3",
    "Up - F4",
    "Up - F",
    "Up - V1a",
    "Up - V1b",
    "Up - V1",
    "Up - V2a",
    "Up - V2b",
    "Up - V2c",
    "Up - V2",
    "Up - V3a",
    "Up - V3b",
    "Up - V3",
    "Up - V4",
    "Up - V",
    "Up - A1a",
    "Up - A1b",
    "Up - A1c",
    "Up - A1d",
    "Up - A1",
    "Up - A2a",
    "Up - A2b",
    "Up - A2",
    "Up - A3a",
    "Up - A3",
    "Up - A4",
    "Up - A",
    # Internal ---------------------------------------------------------------
    "In - R1a",
    "In - R1b",
    "In - R1",
    "In - R2",
    "In - R3",
    "In - R4",
    "In - R5",
    "In - R",
    "In - C1a",
    "In - C1b",
    "In - C1c",
    "In - C1",
    "In - C2",
    "In - C3",
    "In - C4",
    "In - C",
    "In - F1a",
    "In - F1b",
    "In - F1c",
    "In - F1",
    "In - F2a",
    "In - F2b",
    "In - F2",
    "In - F3a",
    "In - F3",
    "In - F4",
    "In - F",
    "In - V1a",
    "In - V1b",
    "In - V1c",
    "In - V1",
    "In - V2a",
    "In - V2b",
    "In - V2c",
    "In - V2",
    "In - V3a",
    "In - V3b",
    "In - V3",
    "In - V4",
    "In - V",
    "In - A1a",
    "In - A1b",
    "In - A1",
    "In - A2a",
    "In - A2b",
    "In - A2",
    "In - A3a",
    "In - A3b",
    "In - A3",
    "In - A4",
    "In - A",
    # Downstream -------------------------------------------------------------
    "Do - R1a",
    "Do - R1b",
    "Do - R1c",
    "Do - R1",
    "Do - R2",
    "Do - R3",
    "Do - R4",
    "Do - R5",
    "Do - R",
    "Do - C1a",
    "Do - C1b",
    "Do - C1c",
    "Do - C1",
    "Do - C2",
    "Do - C3",
    "Do - C4",
    "Do - C",
    "Do - F1a",
    "Do - F1b",
    "Do - F1c",
    "Do - F1",
    "Do - F2a",
    "Do - F2",
    "Do - F3a",
    "Do - F3b",
    "Do - F3",
    "Do - F4",
    "Do - F",
    "Do - V1a",
    "Do - V1b",
    "Do - V1c",
    "Do - V1",
    "Do - V2a",
    "Do - V2b",
    "Do - V2",
    "Do - V3a",
    "Do - V3",
    "Do - V4",
    "Do - V",
    "Do - A1a",
    "Do - A1b",
    "Do - A1c",
    "Do - A1",
    "Do - A2a",
    "Do - A2b",
    "Do - A2",
    "Do - A3a",
    "Do - A3",
    "Do - A4",
    "Do - A",
    # Summary ----------------------------------------------------------------
    "Overall SCRes",
    "Hash",
    "RowChecked",
]


# ---------------------------------------------------------------------------
# Fictional respondents — no real data
# ---------------------------------------------------------------------------
def _row(name, function, company, country, email, scores_seed):
    """Build one data row.  scores_seed shifts all score values slightly."""
    s = scores_seed  # 0, 1, or 2
    v = lambda base: min(5, max(1, base + s - 1))  # noqa: E731

    # 97 score values matching the HEADERS score columns in order
    scores = [
        # Up R
        v(4),
        v(3),
        v(4),
        3.67,
        v(3),
        v(4),
        v(2),
        v(3),
        3.17,
        # Up C
        v(5),
        v(4),
        v(5),
        4.67,
        v(4),
        v(5),
        v(4),
        4.56,
        # Up F
        v(3),
        3.0,
        v(2),
        v(3),
        2.5,
        v(4),
        v(3),
        3.5,
        v(4),
        3.25,
        # Up V
        v(4),
        v(5),
        4.5,
        v(3),
        v(4),
        v(5),
        4.0,
        v(4),
        v(5),
        4.5,
        v(4),
        4.25,
        # Up A
        v(3),
        v(4),
        v(3),
        v(4),
        3.5,
        v(4),
        v(5),
        4.5,
        v(3),
        3.0,
        v(4),
        3.5,
        # In R
        v(4),
        v(3),
        3.5,
        v(4),
        v(3),
        v(4),
        v(5),
        3.875,
        # In C
        v(5),
        v(4),
        v(4),
        4.33,
        v(4),
        v(5),
        v(3),
        4.11,
        # In F
        v(3),
        v(4),
        v(2),
        3.0,
        v(3),
        v(4),
        3.5,
        v(4),
        4.0,
        v(3),
        3.5,
        # In V
        v(4),
        v(3),
        v(5),
        4.0,
        v(4),
        v(3),
        v(4),
        3.67,
        v(5),
        v(4),
        4.5,
        v(3),
        4.04,
        # In A
        v(3),
        v(4),
        3.5,
        v(4),
        v(3),
        3.5,
        v(4),
        v(5),
        4.5,
        v(3),
        3.75,
        # Do R
        v(4),
        v(4),
        v(5),
        4.33,
        v(3),
        v(4),
        v(3),
        v(4),
        3.83,
        # Do C
        v(4),
        v(5),
        v(4),
        4.33,
        v(3),
        v(4),
        v(5),
        4.11,
        # Do F
        v(3),
        v(4),
        v(3),
        3.33,
        v(4),
        4.0,
        v(3),
        v(4),
        3.5,
        v(5),
        3.96,
        # Do V
        v(5),
        v(4),
        v(5),
        4.67,
        v(4),
        v(3),
        3.5,
        v(4),
        4.0,
        v(5),
        4.17,
        # Do A
        v(3),
        v(4),
        v(3),
        3.33,
        v(4),
        v(5),
        4.5,
        v(4),
        4.0,
        v(3),
        3.71,
        # Summary
        3.78 + s * 0.1,
        f"SAMPLE-{s + 1:04d}",
        True,
    ]

    meta = [
        "2024-01-15",
        False,
        name,
        function,
        company,
        country,
        email,
        "Versie 1.0 (eng)",
        "Manufacturing",
        "Manufacture of food products",
        "[500-999]",
        "Operational Excellence",
        "Own company",
        "Center (consumer products)",
        "B2B",
        "[100-499]",
        "[50-99]",
        "[100-499]",
        "[50-99]",
        "Make to stock (MTS)",
        "Market culture – the results-oriented, competitive - Compete Culture",
        "Corporation",
        "Regional",
        "National",
    ]
    return meta + scores


RESPONDENTS = [
    _row(
        "Alice Bennett",
        "Supply Chain Director",
        "Acme Logistics BV",
        "Netherlands",
        "alice.bennett@example.com",
        0,
    ),
    _row(
        "Bob Hartley",
        "Operations Manager",
        "Globex Manufacturing GmbH",
        "Germany",
        "bob.hartley@example.com",
        1,
    ),
    _row(
        "Carol Diaz",
        "Procurement Lead",
        "Initech Solutions NV",
        "Belgium",
        "carol.diaz@example.com",
        2,
    ),
]


def build(out: Path = OUT) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "MasterData"
    # Row 0: one metadata cell (mimics real file)
    ws.append(["Updating: READY"])
    # Row 1: real headers
    ws.append(HEADERS)
    # Rows 2–4: anonymised respondents
    for respondent in RESPONDENTS:
        ws.append(respondent)
    wb.save(out)
    print(f"[OK] Written {len(RESPONDENTS)} rows to {out}")


if __name__ == "__main__":
    build()
